import Vue from "vue";
import Page from "~/components/Page.vue";
import Teaser from "~/components/Teaser.vue";
import Grid from "~/components/Grid.vue";
import Feature from "~/components/Feature.vue";
import FeaturedArticles from "~/components/FeaturedArticles.vue";
import ArticleTeaser from "~/components/ArticleTeaser.vue";
import Photo from "~/components/Photo.vue";
import Slider from "~/components/Slider.vue";
import Slide from "~/components/Slide.vue";
import CButton from "~/components/CButton.vue";
import Product from "~/components/Product.vue";
import ProductTeaser from "~/components/ProductTeaser.vue";
import Collection from "~/components/Collection.vue";
import Heading from "~/components/Heading.vue";

Vue.component("page", Page);
Vue.component("teaser", Teaser);
Vue.component("grid", Grid);
Vue.component("feature", Feature);
Vue.component("featured-articles", FeaturedArticles);
Vue.component("article-teaser", ArticleTeaser);
Vue.component("photo", Photo);
Vue.component("slider", Slider);
Vue.component("slide", Slide);
Vue.component("cbutton", CButton);
Vue.component("blok-product", Product);
Vue.component("collection", Collection);
Vue.component("product-teaser", ProductTeaser);
Vue.component("heading", Heading);
